name: PNPM Dev Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # 每天 8:00 触发

jobs:
  pnpm-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 0.5 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Generate random delay
        id: random-delay
        run: |
          delay=$((RANDOM % 6))
          echo "::set-output name=delay::$delay"

      - name: Wait for random delay
        run: |
          delay=${{ steps.random-delay.outputs.delay }}
          echo "Waiting for $delay minutes..."
          sleep $((delay * 60))

      - name: Install dependencies
        run: npm install

      - name: Run npm dev
        env:
          JD_COOKIE_VALUE: ${{ secrets.JD_COOKIE_VALUE }}
        run: |
          echo "Starting npm run dev..."
          timeout 30s npm run dev || true 
          echo "Task completed or timed out after 30 seconds"    
